import { nanoid } from "nanoid";

export const TECH_DATA = [
  {
    id: nanoid(),
    image: "/techs/html.png",
    name: "HTML",
    text: "#FFFFFF",
    bg: "#EC571E",
  },
  {
    id: nanoid(),
    image: "/techs/css.png",
    text: "#FFFFFF",
    name: "CSS",
    bg: "#3472A8",
  },
  {
    id: nanoid(),
    image: "/techs/js.png",
    text: "#000",
    name: "JAVASCRIPT",
    bg: "#F7E318",
  },
  {
    id: nanoid(),
    image: "/techs/react.png",
    text: "#FFFFFF",
    name: "react",
    bg: "#211F20",
  },
  {
    id: nanoid(),
    image: "/techs/git-icon.png",
    text: "#FFFFFF",
    name: "GIT",
    bg: "#000000",
  },
  {
    id: nanoid(),
    image: "/techs/github.png",
    text: "#000",
    name: "github",
    bg: "#E04B32",
  },
  {
    id: nanoid(),
    image: "/techs/nodejs.png",
    text: "#FFFFFF",
    name: "nodejs",
    bg: "#42463B",
  },
  {
    id: nanoid(),
    image: "/techs/express.png",
    text: "#FFFFFF",
    name: "express",
    bg: "#838283",
  },
  {
    id: nanoid(),
    image: "/techs/mongodb.png",
    text: "#000",
    name: "mongodb",
    bg: "#F1F2F1",
  },
  {
    id: nanoid(),
    image: "/techs/nextjs.png",
    text: "#000",
    name: "next.js",
    bg: "#FFFFFF",
  },
  {
    id: nanoid(),
    image: "/techs/rnative.png",
    text: "#FFFFFF",
    name: "react native",
    bg: "#000",
  },
];
