import Head from "next/head";
import Card from "../components/Card/Card";
import Footer from "../components/Footer/Footer";
import Info from "../components/Info/Info";
import NavBar from "../components/NavBar/NavBar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-transparent.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <NavBar />
      <Info />
      <div className={styles.wrapper}>
        <Card />
      </div>
      <Footer />
    </div>
  );
}
